const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

function writeNotices(root) {
  const go = (args) => execFileSync('go', args, { cwd: root, encoding: 'utf8' }).trim();
  const goroot = go(['env', 'GOROOT']);
  const dependencies = go(['list', '-deps', '-f', '{{if .Module}}{{if not .Module.Main}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}{{end}}', './cmd/sqlite-lens']);
  const sections = [
    'Third-party notices for the bundled SQLite Lens Go executables.\nGenerated by scripts/notices.js.',
    `Go runtime\n\n${fs.readFileSync(path.join(goroot, 'LICENSE'), 'utf8').trim()}`,
  ];

  for (const dependency of [...new Set(dependencies.split('\n').filter(Boolean))].sort()) {
    const [name, version, directory] = dependency.split('|');
    const license = fs.readFileSync(path.join(directory, 'LICENSE'), 'utf8').trim();
    sections.push(`${name} ${version}\n\n${license}`);
  }
  sections.push('SQLite is in the public domain. https://sqlite.org/copyright.html');
  fs.writeFileSync(path.join(root, 'THIRD_PARTY_NOTICES.txt'), sections.join('\n\n' + '-'.repeat(72) + '\n\n') + '\n');
}

module.exports = { writeNotices };
